### ISSUE TITLE
[Exports] Add exports configuration to YAML spec

### ISSUE THREAD

**Issue by courtneyholcomb** [dbt-labs/dbt-semantic-interfaces#189]
### Housekeeping

- [X] I am a maintainer of dbt-semantic-interfaces

### Short description

Add `exports` options to YAML spec.

### Acceptance criteria

YAML for exports should look like the following (nested under `saved_queries`):
```
saved_queries:
  - name: my_query
    description:
    query:
      metrics:
        -
      group_bys:
        - TimeDimension()
        - ...
      where:
        -
    exports:
      - name: my_query 
         config:
           export_as: table # options: table, view - FUTURE: incremental_table, window_table, file
           schema: my_schema  # [optional - DEFAULT to deployment schema]
           alias: some_table_name # [optional - DEFAULT to export name]
```

### Impact to Other Teams

N/A

### Will backports be required?

No
