### ISSUE TITLE
[Feature] Add spec changes for conversion metrics

### ISSUE THREAD

**Issue by WilliamDee** [dbt-labs/dbt-semantic-interfaces#210]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The following will encompass the spec changes for conversion metrics.
```yaml
metric:
  ...
  type_params:
    conversion_type_params:
      entity: _entity_ # required
      base_measure: _measure_ # required
      conversion_measure: _measure_ # required
      calculation: _calculation_type_ # optional. default: conversion_rate. options: conversions(buys) or conversion_rate (buys/visits) + more to come
      window: _time_window_ # optional. default: inf. window to join the two events on. Follows similar format as time windows elsewhere (i.e. 7 days)
      constant_properties: # optional. List of constant properties default: None
        - name: _string_ # optional.
          base_expr: _string_ # optional. Even if name above is expressed. defaults to name above. solves for role also
          conversion_expr: _string_ # same as base above
```

### Who will this benefit?

Enables the SL to build conversion metrics
