### ISSUE TITLE
[Feature] Add config block to saved queries to flag a saved query as enabled/disabled for the declarative cache.

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/dbt-semantic-interfaces#237]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

**Declarative Cache**
The Declarative Cache stores saved queries that a user specifies (declares) in the data warehouse. The basic flow for populating and reading from this cache is:  

    - Saved Query → Orchestration → Build table → Same Query → Select * from table

The declarative cache will be specified in the config object under a saved query. This gives us the benefit of defaulting to all saved queries being cached or not and for that flag to be flipped the other way in any given saved query.

```yaml
saved_queries:
  - name: my_query
      description:
      query_params:
          *...*
      exports:
          *...*
    config:
      cache:
        enabled: true|false
```

This allows us to keep a clean distinction for an export which is not under our management vs. a cache that is purely under our management.
