### ISSUE TITLE
[Feature] Add cache config to saved query

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/dbt-semantic-interfaces#252]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

To enable declarative caching you need to be able to specify if a saved query should be used to populate the cache. Users can set cache: enabled: true | enabled as a configuration of a saved query. The saved query spec is below:
```
saved_queries:
	- name: my_query
		description:
		query_params:
			...
		exports:
			...
                config:
                  cache:
                    enabled: true|false
``` 

### Who will this benefit?

Users who want to increase the performance of saved queries.
