### ISSUE TITLE
[Feature] Custom calendar support

### ISSUE THREAD

**Issue by courtneyholcomb** [dbt-labs/dbt-semantic-interfaces#335]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Support custom calendar spec in time spine.
```
time_spine:
  standard_granularity_column: date_day
  custom_granularity_columns:
      - name: fortnight
      - name: retail_month
      - name: fiscal_quarter
```
