### ISSUE TITLE
[Spec Update] Support inline metric definitions

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-semantic-interfaces#56]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Say you want to define a derived metric that is a ratio of two measures. In the old world you'd use a ratio metric type but that will no longer exist. So you have two options:
- Define each measure as its own simple metric with create_metric: true
- **ADDITION**: Define the simple metrics inline with the derived metric definition. 

```yaml
metric:
  name: derived_metric
  type: derived
  type_params:
    expr: "metric_a / metric_b"
    metrics:
      - name: metric_a
        type: simple
        type_params:
         - measure: column_a

      - name: metric_b
        type: simple
        type_params:
         - measure: column_b
```

In the above example, metric_a and metric_b would NOT show up in `list-metrics` as they are only defined inline to derived_metric. Similar to how dbt uses ephemeral models today.
